{{- if and .Values.magicLink.persistence.enabled (not .Values.magicLink.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "magicLink.fullname" . }}-data
  labels:
    {{- include "magicLink.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.magicLink.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.magicLink.persistence.size | quote }}
  {{- if .Values.magicLink.persistence.storageClassName }}
  storageClassName: {{ .Values.magicLink.persistence.storageClassName | quote }}
  {{- end }}
{{- end }}

